# must be unique in a given SonarQube instance  注意必须唯一
sonar.projectKey=jw_web_demo222
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=jw_web_demo222
sonar.projectVersion=1.0 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set.
#.点代表扫描当前路径下所以路径
sonar.sources=. 
# 这里是排除当前路径下的test和target文件夹
sonar.exclusions=**/test/**,**/target/** 
sonar.java.source=1.8 
sonar.java.target=1.8 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8